version: '3'
services:
  localhost:
    image: rabbitmq:latest
    ports:
        - 5673:5672
        - 15673:15672
    #volumes:
        #- ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        #- ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_nodejs

  api:  
    depends_on:
      - localhost
    build: 
      dockerfile: Dockerfile
      context: ./
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - "8080:8080"
  
    environment:
      - HOST=mongodb+srv://bosta:bosta@cluster0.r4tfj3d.mongodb.net/?retryWrites=true&w=majority
      - SECRET_TOKEN=bosta
      - EMAIL_USERNAME=adel.essam.elfar@gmail.com
      - EMAIL_PASSWORD=Real_Madrid1
      - PORT=8080
      - CLIENT_ID=637679613688-jbc824747ff9544cofclvkrab14seomp.apps.googleusercontent.com
      - CLIENT_SECRET=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
      - REFRESH_TOKEN=1//04CwM4StXddt2CgYIARAAGAQSNwF-L9IrHqU2e_1oXiUgJDYyMY7DvtQwTTLI6Vrnly8WrV25yfOWW91HLzSyVfPTuhWz-c0421U
      - ACCESS_TOKEN = ya29.a0AVvZVsoagqtFcA2xxa2-ZRg9DtAgODnIZwKGgIFbYwX5Dsf2y5gWJpPCE9GySpMjBRLDf68vDXs-xdZY2moszqKryshkrFbWr5Vdlyynb3eoOUL9VZgRNeacrzIITmYmiSOn3ezCpJo8Ezp5ehbHpXZH-Q46aCgYKAbwSARESFQGbdwaInj1HqIWz7oKysQzpJeKgYw0163


networks:
  rabbitmq_nodejs:
    driver: bridge